spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: "test"
    password: "test"
  jpa:
    hibernate:
      ddl-auto: update

# enable e controlla se corretto
logging:
  level:
    root: WARN
    org.hibernate: INFO
    org.springframework:
      core: WARN
      web: WARN
