spring:
  main:
    lazy-initialization: true
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: "test"
    password: "test"
  jpa:
    hibernate:
      # https://docs.spring.io/spring-boot/docs/1.3.5.RELEASE/reference/html/howto-database-initialization.html
      # update: 
      ddl-auto: update

server:
  port: 3004


# ERROR, WARN, INFO, DEBUG, or TRACE.
logging:
  level:
    root: error
    org.hibernate:
      # https://www.baeldung.com/sql-logging-spring-boot
      SQL: info
      type:
        descriptor:
          sql:
            BasicBinder: error
    org.springframework:
      core: error
      beans: error
      context: error
      transaction: error
      test: error
      web: error

    com.flowautomator.controllers: error
